### ISSUE TITLE
Style.css not exported for Text Layer Implementation

### ISSUE THREAD

**Issue by adi-dora** [TaTo30/vue-pdf#101]
I'm running the VuePDF module and when I try importing the style.css like the documentation, I get an error:

![image](https://github.com/TaTo30/vue-pdf/assets/33942249/c9e5fa9c-5e73-4260-a81e-5438432d3de0)

Here's my code:
```
<script lang="ts" setup>
import { useQuasar } from 'quasar';
import { VuePDF, usePDF } from '@tato30/vue-pdf';
import '@tato30/vue-pdf/style.css';
import { ref, onBeforeMount, watch, reactive } from 'vue';
import VCodeBlock from '@wdns/vue-code-block';
import VueCookies from 'vue-cookies';
```

Any advice would be helpful, thanks!

**Comment by TaTo30** [comment]
It could be an issue from vite, the `package.json` exports are defined like this:
```json
"exports": {
    ".": {
      "require": "./dist/index.umd.js",
      "import": "./dist/index.mjs",
      "types": "./dist/types/index.d.ts"
    },
    "./*.css": "./dist/*.css",
    "./src/*": "./src/*"
  }
```

Try modifying this line `"./*.css": "./dist/*.css"` by `"./style.css": "./dist/style.css"`

**Comment by adi-dora** [comment]
OK yes, that does fix it for me locally, thank you! But, when I actually deploy, the same error persists because the version of the module that gets installed still has the issue. Do you have any fix for this?
