### ISSUE TITLE
Switching between multiple PDFs causes crash

### ISSUE THREAD

**Issue by courdek** [TaTo30/vue-pdf#103]
When loading and switching between multiple PDFs, the browser tab will crash after `n` times. This can be reproduced on the documentation page by clicking "Next PDF" approximately 30 times (I imagine this will vary depending on the computer).

Inspecting the memory usage shows a new Javascript VM instance being created every time the PDF is changed. Essentially it acts like a memory leak. Eventually it overwhelms the tab and crashes. 

**Additional context**
![image](https://github.com/TaTo30/vue-pdf/assets/319738/fbe56852-bdbc-49d9-aebb-177dded599b9)
![image](https://github.com/TaTo30/vue-pdf/assets/319738/823ca679-8dd7-41b7-9501-9f5d3d36f9c4)

**Comment by GuoyiCoding** [comment]
I used `PDFDocumentProxy.destory()` to destroy the previous document instance and terminate the worker when source of pdf has changed.

Now, it seems that every JavaScript VM instance created before can be destroyed normally.

Before
![before](https://github.com/TaTo30/vue-pdf/assets/15711704/843cf1a4-4d70-4536-8e87-72d180b87767)

After
![after](https://github.com/TaTo30/vue-pdf/assets/15711704/ea726741-3677-4d79-9241-087e4496f43f)

see [https://github.com/TaTo30/vue-pdf/pull/105](url)
