### ISSUE TITLE
Cannot set properties of undefined (setting 'workerSrc')

### ISSUE THREAD

**Issue by YaoZhouZ** [TaTo30/vue-pdf#108]
File:
    /Users/edy/Desktop/project/lightpdf/node_modules/.pnpm/@tato30+vue-pdf@1.9.6_vue@3.4.20/node_modules/@tato30/vue-pdf/dist/index.mjs:741:35
  Code:
    740 | function vl(l) {
    > 741 |   D.GlobalWorkerOptions.workerSrc = l;
          |                                   ^
      742 | }
      743 | function fl(l, d = {
      744 |   onProgress: void 0,
  Stacktrace:

**Comment by TaTo30** [comment]
That error is common when SSR frameworks are used, Try wrapping the component with some "client-only" component or directive.

**Comment by YaoZhouZ** [comment]
![image](https://github.com/TaTo30/vue-pdf/assets/100512476/68511a4d-769d-45ec-b948-dda8d62f96b1)

**Comment by TaTo30** [comment]
I have not used astro but after some research I found this:

![imagen](https://github.com/TaTo30/vue-pdf/assets/57086025/eb1eca86-5c57-4436-b073-c24657d72188)
