### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'then')

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [TaTo30/vue-pdf#119]
I have tried reading all issues and no solution to this yet

**Additional context**
 - vue-pdf: 1.10.0
 - vue: 3.0.5

<img width="492" alt="Screenshot 2024-06-12 at 15 36 26" src="https://github.com/TaTo30/vue-pdf/assets/29608698/9c485080-cabf-4417-b237-44c3ccc69ca6">

<img width="525" alt="Screenshot 2024-06-12 at 15 37 40" src="https://github.com/TaTo30/vue-pdf/assets/29608698/deae835b-6c87-4fd3-a49a-a92a22397d84">

**Comment by quinn50311** [comment]
I have same problem.

**Comment by timmaier** [comment]
I am also experiencing same issue:

Have a file upload that I watch and create a object url from which is then pass to usePDF.

Issue was also apparent on 1.9.7 as well as 1.10.0

**Comment by diego-lipinski-de-castro** [comment]
Have you guys found a fix?

**Comment by InnaForkert** [comment]
> Have you guys found a fix?

It somehow helped me to use usePDF(url).pdf instead of destructuring, yet I don't know why. Hope this gives you a lead

**Comment by TaTo30** [comment]
I see the problem could be this line:
```js
pdfPath2.value = pdf
```

`pdf` is an already `ref` object, so you don't need to reassign to another `ref` object, but if you need save the values in another variables the first thing to know is that usePDF loads the content asynchronously, in order to get the values synchronously you need the watch the values like this:

```js
const { pdf, pages } = usePDF(pdfcontent)

watch([pdf, pages], ([pdfval, pagesval]) => {
    pdfPath2.value = pdfval;
    pdfPages.value = pagesval;
    pdfForm.file = file
});
```

**Comment by diego-lipinski-de-castro** [comment]
Thanks @TaTo30! I ended up approaching the problem in a slightly different way, but you response solved the issues!

Here is the current working code for my use case:

<img width="554" alt="Screenshot 2024-07-01 at 10 07 47" src="https://github.com/TaTo30/vue-pdf/assets/29608698/07d55a34-982c-4da3-b064-9aa6a0dab0ea">
