### ISSUE TITLE
Loading the pdf is too slow. It takes more than 10 seconds. Is there any best way?

### ISSUE THREAD

**Issue by kingcwt** [TaTo30/vue-pdf#121]
My requirement is to jump to a specified page number

**Comment by longnight** [comment]
Same. My cases are scale up or down, it re-rendered so slow. Anyone have solution ?

**Comment by YaoZhouZ** [comment]
I also have this problem. When I load a PDF of 30M or more than 1000 pages, it will load very slowly, and when I dynamically adjust the width of the PDF, it will also load very slowly. Is there a solution to this problem?

**Comment by kingcwt** [comment]
Use pdf-object, this is the official website address, but it does not support highlighting. Rendering pdf is okay and acceptable.

**Comment by kingcwt** [comment]
The one I am currently using has a lot of pitfalls, and the highlights are not displayed properly in many places, so I have given up using this and changed to pdf-object. I will close this problem. If you have other questions, please reopen it.
