### ISSUE TITLE
Error with Vite

### ISSUE THREAD

**Issue by stefanwuthrich** [TaTo30/vue-pdf#124]
With:
- vue-pdf 1.10.0
- vue 3.4.27
- vite 5.3.3
I get this below, when I run yarn dev 

[ERROR] Top-level await is not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari14" + 2 overrides)

    node_modules/pdfjs-dist/build/pdf.mjs:19764:53:
      19764 │ ...rts__ = globalThis.pdfjsLib = await (globalThis.pdfjsLibPromise =...
            ╵                                  ~~~~~

that did not happen with earlier vite/vue versions

**Comment by stefanwuthrich** [comment]
thank you very much. resolved.

**Comment by FourLeafClover** [comment]
@stefanwuthrich
 if you are use vite,  the  plugin vite-plugin-top-level-await can fix problem.
