### ISSUE TITLE
referencedPage set as NaN for internal-links on a pdf generated by Adobe

### ISSUE THREAD

**Issue by GinoVillalpando** [TaTo30/vue-pdf#126]
In a recent project, I was given a task to use internal links to jump to a specific page. When using the `internal-link` event type I noticed the `referencedPage` was always coming back as `NaN` and would break the entire pagination. I noticed the document was generated originally using Adobe inDesign which I'm not too familiar with but is probably another text document editor. I added the links but in Microsoft Word this time and that worked perfectly fine. I'm assuming there are different methods when setting links to a specific spot in the pdf and could even be a bug with pdf.js. Thank you for looking into it🙏

**Additional context**
 - vue-pdf: ^1.10.0
 - vue: 3

```typescript
if (event.type === 'internal-link') {
    page.value = parseInt(event.data.referencedPage);
}
```

**Comment by GinoVillalpando** [comment]
further context: the regular `link` event type worked fine for navigating to the specified URL on the pdf generated by Adobe inDesign

**Comment by TaTo30** [comment]
> further context: the regular link event type worked fine for navigating to the specified URL

I get confused 😅, did the `link` event work fine with external links like `mailto`, `https`, etc?

Could you share a PDF with those links generated by Adobe inDesign?, so I could do some research about it.

**Comment by GinoVillalpando** [comment]
> > further context: the regular link event type worked fine for navigating to the specified URL
> 
> I get confused 😅, did the `link` event work fine with external links like `mailto`, `https`, etc?
> 
> Could you share a PDF with those links generated by Adobe inDesign?, so I could do some research about it.

Yes the `link` event worked with external links made from Adobe inDesign it was only the `internal-links` that link to another page in the pdf

[FAQ_03.pdf](https://github.com/user-attachments/files/16183883/FAQ_03.pdf)
