### ISSUE TITLE
ram full and slow when change pdf file

### ISSUE THREAD

**Issue by leontecluyen** [TaTo30/vue-pdf#130]
*.vue file 

import { VuePDF, usePDF } from '@tato30/vue-pdf'

VuePDF :pdf="pdf" class="test"

script 
const fileURL = ref('')
const { pdf } = usePDF(fileURL)

const setURL = () =>
{
	fileURL.value = applyData.value.rent_file_url
}

---> applyData is response from api
when call api many times it so slow
sorry for my bad english

**Comment by TaTo30** [comment]
Please, share the PDF file and a code example to reproduce the issue.

**Comment by deepfaith** [comment]
Hi, I hope there's a fix on this it seems the highlighting causes ram to utilize full usage.

Btw, thanks for the package, it helps me a lot!
