### ISSUE TITLE
Docs: add info about Node v22+ for nuxt projects

### ISSUE THREAD

**Issue by romanhrynevych** [TaTo30/vue-pdf#137]
After updating your package to v1.11.0 I was facing issue:
<img width="1039" alt="image" src="https://github.com/user-attachments/assets/da5fa2b8-2813-4648-8199-2d166a6c7805">

After several hours of debugging I find out that it was inside `pdfjs-dist` update, which starts using `Promise.withResolvers` which available in Node v22+

Could you please add this in Readme, so users will know what could cause this issue 🙂

**Comment by TaTo30** [comment]
Hi,

Added to README.md
