### ISSUE TITLE
electron webapp error

### ISSUE THREAD

**Issue by ouynle** [TaTo30/vue-pdf#138]
vue:12 Refused to load the script 'data:application/javascript;base64,LyoqCiAqIEBsaWNzdGFydCBUaGUgZm9sbG93aW5n…dvcmtlck1lc3NhZ2VIYW5kbGVyO2V4cG9ydHt5ZyBhcyBXb3JrZXJNZXNzYWdlSGFuZGxlcn07' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

**Comment by TaTo30** [comment]
Try adding `script-src 'data:'` to the CSP header.

**Comment by ouynle** [comment]
Good thank you

**Comment by ouynle** [comment]
Can I add you on Telegram? Thank you.
