### ISSUE TITLE
Upgrading from 1.10.0 to 1.11.0 vue-pdf gives error

### ISSUE THREAD

**Issue by NetMango** [TaTo30/vue-pdf#145]
Hi.

Upgrading from  1.10.0 to 1.11.0 version vue-pdf gives error:

```
client-entry.js:126 TypeError: Cannot set properties of undefined (setting '_isSameOrigin')
    at <static_initializer> (@tato30_vue-pdf.js?v=e3e01c02:11779:30)
    at @tato30_vue-pdf.js?v=e3e01c02:11750:18
```

Version 1.10.0 works well. 
Please Check it out, thank you.

**Comment by TaTo30** [comment]
Surely is related to #142, update to latest version and try again, if the error persists reopen the issue.
