### ISSUE TITLE
Incorrect relative path for loading-icon.2cb588dc.svg causes 404 error

### ISSUE THREAD

**Issue by Bronco84** [TaTo30/vue-pdf#150]
#### Description: 
There's a loading icon ```loading-icon.2cb588dc.svg``` embedded as a base64-encoded SVG in the code. However, the system is incorrectly referencing it using a relative path, which causes a 404 error.

#### Steps to Reproduce:

1. Load a pdf into the viewer.
2. Inspect the network requests using the browser's developer tools.
3. Observe that the request for loading-icon.2cb588dc.svg returns a 404 error.

#### Expected Behavior: 
The Base64-encoded SVG should be directly used for the loading icon, without requiring any network requests. The browser should display the icon without attempting to retrieve it from the server.

#### Actual Behavior: 
The system attempts to retrieve the loading-icon from a relative path, which results in a 404 error.

#### Suggested Fix: 
Ensure that the Base64-encoded SVG is correctly embedded in the code, and that the image is referenced directly, preventing a failed network request.

![Screenshot 2024-09-20 at 3 11 42 PM](https://github.com/user-attachments/assets/f3dfd088-9c54-4ebb-8473-a0b112fedfaa)

**Additional context**
 - vue-pdf:  1.0.3
 - vue: 3.5.5

**Comment by TaTo30** [comment]
This seems to be an implementation issue. If your pdf needs to load images consider use [image-resource-path prop](https://tato30.github.io/vue-pdf/guide/props.html#image-resources-path) to retrieve them correctly.
