### ISSUE TITLE
Fix text layer selections overlaying each other & falsely ignoring some empty/blank space

### ISSUE THREAD

**Issue by IllustrisJack** [TaTo30/vue-pdf#158]
First of all, thank you for this project! Great stuff.

As title says the text layer selections could be improved which is currently for better or worse depending on the PDF. Can also be found in the example uploaded on your [docs](https://tato30.github.io/vue-pdf/examples/basic/text_layer.html). I´d assume this comes from certain blank spaces being ignored/hard cut e.g. also for `newline`. 

![image](https://github.com/user-attachments/assets/a195af13-9cbf-4d77-8d7d-b3b3fffc2765) 

**Additional context**
 - vue-pdf: 1.11.2
 - vue: latest

**Comment by TaTo30** [comment]
Hi, sorry for taking too long to reply.

> As title says the text layer selections could be improved which is currently for better or worse depending on the PDF. Can also be found in the example uploaded on your [docs](https://tato30.github.io/vue-pdf/examples/basic/text_layer.html). I´d assume this comes from certain blank spaces being ignored/hard cut e.g. also for newline.

Are you using a chrome-based browser? this issue seems to be more related on how the browser "paint" the selection layer, in firefox the selection looks better:

![imagen](https://github.com/user-attachments/assets/41cf35b7-6bec-4ff6-9e0a-8d6bd451c4f0)

Also, this library does not make any treatment to the text-layer it just use the `pdf.js` api without changing the text items, maybe for chrome I could try to do some clean process but I am aware that it could break other things just for something aesthetic.

**Comment by IllustrisJack** [comment]
> Hi, sorry for taking too long to reply.
> 
> > As title says the text layer selections could be improved which is currently for better or worse depending on the PDF. Can also be found in the example uploaded on your [docs](https://tato30.github.io/vue-pdf/examples/basic/text_layer.html). I´d assume this comes from certain blank spaces being ignored/hard cut e.g. also for newline.
> 
> Are you using a chrome-based browser? this issue seems to be more related on how the browser "paint" the selection layer, in firefox the selection looks better:
> 
> ![imagen](https://private-user-images.githubusercontent.com/57086025/383810171-41cf35b7-6bec-4ff6-9e0a-8d6bd451c4f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODczNzIsIm5iZiI6MTczMDk4NzA3MiwicGF0aCI6Ii81NzA4NjAyNS8zODM4MTAxNzEtNDFjZjM1YjctNmJlYy00ZmY2LTllMGEtOGQ2YmQ0NTFjNGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDEzNDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjZDdjODcwYTFkNDFhOTZiNzRkZjQ3MGUzM2JjMzA1ZGJmMzViOWU4YjQ0NGQxYzE2YzkyY2NmYTJhYjAzMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4hW9L03IqSmoRG6vFwqfn1TYqOK4JrZOht8gEjuWlv4)
> 
> Also, this library does not make any treatment to the text-layer it just use the `pdf.js` api without changing the text items, maybe for chrome I could try to do some clean process but I am aware that it could break other things just for something aesthetic.

Thanks for the reply and no worries for taking long, I am sure all of this is in your free time! Yes I was using multiple chromium based browsers when testing this. 
I guess it is mostly for aesthetic reasons, but functionally we are also missing out on empty spaces when copying text from the text layer in the current state. 

Interestingly when testing pdf.js via the official mozilla demo on the same browsers I wasn´t running in to this issue https://mozilla.github.io/pdf.js/web/viewer.html hence why I opened this issue.

**Comment by TaTo30** [comment]
> I guess it is mostly for aesthetic reasons, so if it is too much work we can close this issue.

Maybe I am not getting you, you said there are some blank spaces that are being ignored on selection but I do not see exactly where. Using the same example, the copy result on this text:

```
1. Introduction
Dynamic languages such as JavaScript, Python, and Ruby, are pop-
ular since they are expressive, accessible to non-experts, and make
deployment as easy as distributing a source file. They are used for
small scripts as well as for complex applications. JavaScript, for
example, is the de facto standard for client-side web programming
Permission to make digital or hard copies of all or part of this work for personal or
classroom use is granted without fee provided that copies are not made or distributed
for profit or commercial advantage and that copies bear this notice and the full citation
on the first page. To copy otherwise, to republish, to post on servers or to redistribute
to lists, requires prior specific permission and/or a fee.
PLDI’09, June 15–20, 2009, Dublin, Ireland.
Copyright c© 2009 ACM 978-1-60558-392-1/09/06. . . $5.00
```

But this result is the same in all cases whether testing on the library docs or pdf.js demo page (even between chromium and firefox browser). Could I missing something?

**Comment by IllustrisJack** [comment]
> > I guess it is mostly for aesthetic reasons, so if it is too much work we can close this issue.
> 
> 
> 
> Maybe I am not getting you, you said there are some blank spaces that are being ignored on selection but I do not see exactly where. Using the same example, the copy result on this text:
> 
> 
> 
> ```
> 
> 1. Introduction
> 
> Dynamic languages such as JavaScript, Python, and Ruby, are pop-
> 
> ular since they are expressive, accessible to non-experts, and make
> 
> deployment as easy as distributing a source file. They are used for
> 
> small scripts as well as for complex applications. JavaScript, for
> 
> example, is the de facto standard for client-side web programming
> 
> Permission to make digital or hard copies of all or part of this work for personal or
> 
> classroom use is granted without fee provided that copies are not made or distributed
> 
> for profit or commercial advantage and that copies bear this notice and the full citation
> 
> on the first page. To copy otherwise, to republish, to post on servers or to redistribute
> 
> to lists, requires prior specific permission and/or a fee.
> 
> PLDI’09, June 15–20, 2009, Dublin, Ireland.
> 
> Copyright c© 2009 ACM 978-1-60558-392-1/09/06. . . $5.00
> 
> ```
> 
> 
> 
> But this result is the same in all cases whether testing on the library docs or pdf.js demo page (even between chromium and firefox browser). Could I missing something?
> 
> 

I think you can safely ignore my statement. Some pdf viewers also add newline as copyable spaces to retain the format. This is not the case with pdf.js so I probably got things confused!
