### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by scramatte** [TaTo30/vue-pdf#59]
Hello,

Does it posible to add features such : fullscreen, adjust to height , adjust to width,  and browse pages thumbnails?

Regards

**Comment by TaTo30** [comment]
Fullscreen and browse pages thumbnails seem like an application-specific features to me, i think those shouldn't be supported by the component.

Regarding sizing features, there is the `fit-parent` that adjust to parent's width, i've been thinking to add a height-related adjusting prop but i still haven't figured out on how its behavior should be, mainly when is combined with width prop.

Any other ideas are always welcome.

**Comment by WebDeveloperBen** [comment]
Just stumbled upon this. What about adding the ability to measure between points on the pdf?

**Comment by TaTo30** [comment]
That is a feature related to annotation editor layer and isn't currently supported by `pdf.js`. If possible, i wouldn't like to implement annotation features outside `pdf.js` scope.

**Comment by WebDeveloperBen** [comment]
That's fair appreciate the speedy response. Do you know of any solutions that aren't having to implement measuring distances on a pdf building plan besides having to implement it myself from scratch?

**Comment by TaTo30** [comment]
I haven't seen solutions like you are looking for. I've only found libraries that measure distances geographically :/
