### ISSUE TITLE
New Request - Displaying External Highlights

### ISSUE THREAD

**Issue by dmnxprss** [TaTo30/vue-pdf#70]
Firstly, thank you very much for creating VuePDF!

I have a question relating to annotations (highlights) which came to me after reviewing the [**react-pdf-highlighter**](https://github.com/agentcooper/react-pdf-highlighter) repo
. Within their react library they are able to display highlights pulling from a json file, which I image you could also pull from a database of saved annotations. 

My question is how would you image/advise someone to replicate this within in your component. Below I have provided an example of one of the highlights from the json file.

Thank You

```
{
      content: {
        text: " Type Checking for JavaScript",
      },
      position: {
        boundingRect: {
          x1: 255.73419189453125,
          y1: 139.140625,
          x2: 574.372314453125,
          y2: 165.140625,
          width: 809.9999999999999,
          height: 1200,
        },
        rects: [
          {
            x1: 255.73419189453125,
            y1: 139.140625,
            x2: 574.372314453125,
            y2: 165.140625,
            width: 809.9999999999999,
            height: 1200,
          },
        ],
        pageNumber: 1,
      },
      comment: {
        text: "Flow or TypeScript?",
        emoji: "🔥",
      },
      id: "8245652131754351",
    },
```

**Comment by TaTo30** [comment]
Recently was published a version with a highlighting feature that provide an event that returns the textDivs and the matches of the text searched, you can check how it works here: https://tato30.github.io/VuePDF/examples/text_events/text_highlight.html#highlight-event, you could use the textDivs to implement that you want but i'm afraid it would be troublesome to workaround.

`pdf.js` was implementing this feature (https://github.com/mozilla/pdf.js/issues/14975) but unfortunaly was closed temporaly :(
