### ISSUE TITLE
Can it support on-demand loading and virtual scrolling to solve the loading and memory consumption issues of large PDF files?

### ISSUE THREAD

**Issue by bzw1204** [TaTo30/vue-pdf#87]
Can it support on-demand loading and virtual scrolling to solve the loading and memory consumption issues of large PDF files?
Here is the reference link： https://github.com/Lemonreds/react-pdf-p2

**Comment by TaTo30** [comment]
On-demand loading requires your API supports range-request and then you can set the `pdf.js`'s behavior using any of [DocumentInitParameter](https://github.com/mozilla/pdf.js/blob/38287d943532eee939ceffbe6861163f93805ca7/src/display/api.js#L145) in `usePDF`.

Regarding scrolling, `VuePDF` component only renders one page so you can control how many pages to render on viewport by using [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)
