### ISSUE TITLE
Highlight a piece of text

### ISSUE THREAD

**Issue by AjaxZhan** [TaTo30/vue-pdf#90]
This js library is very useful for me.However, how can I highlight a piece of text instead of certain words, in other words, can I use this library to highlight an area?

**Comment by TaTo30** [comment]
There aren't a way to highlight an area using the library so far, but if you can get the divs you need to highlight you can append the highlight class:
```js
span.className = 'highlight appended'
```
[highlight.ts](https://github.com/TaTo30/vue-pdf/blob/master/src/components/utils/highlight.ts)

**Comment by TaTo30** [comment]
I will close this Issue since is a duplicate of #98
