### ISSUE TITLE
Chinese Text Not Displaying in vue-pdf

### ISSUE THREAD

**Issue by SuxueCode** [TaTo30/vue-pdf#91]
Hello, I'm encountering some issues while using vue-pdf. It seems that when there is Chinese text in the PDF, the text doesn't display properly, and the browser console shows the following error:
Warning: Error during font loading: CMapReaderFactory not initialized, see the `useWorkerFetch` parameter.

However, I couldn't find any relevant configuration options. Could you please provide some assistance? 
Thank you!

**Comment by TaTo30** [comment]
Hi @SuxueCode, can you share that PDF file?

**Comment by suiusiudis** [comment]
[Uploading 1.pdf…]()

**Comment by suiusiudis** [comment]
[1.pdf](https://github.com/TaTo30/vue-pdf/files/14371649/1.pdf)
This invoice can not be displayed in Chinese
