### ISSUE TITLE
输出警告后导致vue3页面空白

### ISSUE THREAD

**Issue by TsMask** [TaTo30/vue-pdf#96]
![image](https://github.com/TaTo30/vue-pdf/assets/37463159/4a1e3ade-15d0-4850-8e57-30f27382ccfb)

能正常打开pdf显示到页面，控制台输出
Warning: TT: undefined function: 3
随后跳转到新的页面会导致空白，只能F5全局刷新解决

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
vue3.3 
vite5

**Comment by TsMask** [comment]
使用wps生成的pdf

```sh
vite v5.1.4 building for production...
images/altText_add.svg referenced in C:/AMP/Probject/ems_frontend_vue3/node_modules/@tato30/vue-pdf/dist/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

images/altText_done.svg referenced in C:/AMP/Probject/ems_frontend_vue3/node_modules/@tato30/vue-pdf/dist/style.css didn't resolve at build time, it will remain unchanged to be resolved at runtime

node_modules/pdfjs-dist/build/pdf.js (1982:23) Use of eval in "node_modules/pdfjs-dist/build/pdf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
```

以上是打包后的提示信息

打包后dist目标部署nginx正常能显示pdf

控制台还是输出：Warning: TT: undefined function: 3

随后跳转到新页面也可以正常显示，就dev启动时才会有跳转新页面空白的情况

[TestPDF.pdf](https://github.com/TaTo30/vue-pdf/files/14441937/TestPDF.pdf)

**Comment by TaTo30** [comment]
I got that you were able to make your application works in production environment, so I going to close this Issue since there are no errors to be fixed in the component.

If you still have problems feel free to open another Issue.
