### ISSUE TITLE
Add a demo site to this project

### ISSUE THREAD

**Issue by FAbrahamDev** [TaTo30/vue-pdf#97]
I searched the website and README and could not find one example of how this PDF viewer looks, and I can interact with the component.
Adding a demo which shows its capabilities (or at least a screenshot) would help me to decide if I want to switch to this PDF viewer.

**Comment by TaTo30** [comment]
You can find examples in the documentation website: https://tato30.github.io/vue-pdf/

**Comment by TaTo30** [comment]
`vue-pdf` is not a full PDF viewer is only a tool/component to make one.
